In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('uber.xlsx')

df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2025-09-22,06:39:39,T1984811,Cancelled by Customer,C6701334,Auto,Dilshad Garden,Qutub Minar,1.0,Change of plans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-06-14,11:41:45,T2969701,Cancelled by Customer,C1401223,Auto,Delhi Gate,Chandni Chowk,1.0,Change of plans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-10-10,12:56:23,T6336375,Cancelled by Customer,C7874381,Auto,Laxmi Nagar,IGNOU Road,1.0,Change of plans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-07-30,10:39:07,T1997739,Cancelled by Customer,C3565599,Auto,Seelampur,Kalkaji,1.0,Change of plans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-06-15,08:37:03,T9352835,Cancelled by Customer,C4457487,Auto,Manesar,Old Gurgaon,1.0,Change of plans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2025-06-29,22:53:26,T3441703,Completed,C3345887,Auto,Udyog Vihar,Kaushambi,NaN,NaN,NaN,NaN,NaN,NaN,300.0,44.72,4.2,4.9,UPI
149996,2025-05-08,16:36:23,T5412815,Completed,C7457601,Auto,Shastri Nagar,Gurgaon Railway Station,NaN,NaN,NaN,NaN,NaN,NaN,328.0,34.35,4.2,4.9,UPI
149997,2025-07-15,17:16:41,T4359237,Completed,C9229149,Auto,Karol Bagh,Udyog Vihar,NaN,NaN,NaN,NaN,NaN,NaN,141.0,25.40,4.2,4.9,UPI
149998,2025-12-08,09:18:33,T5006207,Completed,C8892560,Auto,Karol Bagh,Vaishali,NaN,NaN,NaN,NaN,NaN,NaN,2045.0,37.85,4.2,4.9,UPI
149999,2025-12-24,19:29:32,T2260698,Completed,C6573059,Auto,Khandsa,Botanical Garden,NaN,NaN,NaN,NaN,NaN,NaN,654.0,5.06,4.2,4.9,UPI

In [6]:
df.shape

(150000, 19)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 19 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  datetime64[ns]
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Cancelled Rides by Customer        10500 non-null   float64
 9   Reason for cancelling by Customer  10500 non-null   object
 10  Cancelled Rides by Driver          27000 non-null   float64
 11  Driver Cancellation Reason         27000 non-null   object
 12  Incomplete Rides                   9000 non-null    float64
 13  Incomplete Rides Reason            9000 non-null    object
 14  Booking Value                      102000 non-null  float64
 15  Ride Distance                      102000 non-null  float64
 16  Driver Ratings                     93000 non-null   float64
 17  Customer Rating                    93000 non-null   float64
 18  Payment Method                     102000 non-null  object
dtypes: datetime64[ns](1), float64(7), object(11)
memory usage: 21.7+ MB

# Rename Columns

In [4]:
print("BEFORE — Column names:")
print(df.columns.tolist())

# Pipeline: lowercase → strip whitespace → replace spaces with underscores
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(' ', '_', regex=False)
)

print("\nAFTER — Standardized column names:")
print(df.columns.tolist())

BEFORE — Column names:
['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID', 'Vehicle Type', 'Pickup Location', 'Drop Location', 'Cancelled Rides by Customer', 'Reason for cancelling by Customer', 'Cancelled Rides by Driver', 'Driver Cancellation Reason', 'Incomplete Rides', 'Incomplete Rides Reason', 'Booking Value', 'Ride Distance', 'Driver Ratings', 'Customer Rating', 'Payment Method']

AFTER — Standardized column names:
['date', 'time', 'booking_id', 'booking_status', 'customer_id', 'vehicle_type', 'pickup_location', 'drop_location', 'cancelled_rides_by_customer', 'reason_for_cancelling_by_customer', 'cancelled_rides_by_driver', 'driver_cancellation_reason', 'incomplete_rides', 'incomplete_rides_reason', 'booking_value', 'ride_distance', 'driver_ratings', 'customer_rating', 'payment_method']

# Check Duplication

In [7]:
total_dups = df.duplicated().sum()
print(f"Total fully duplicate rows: {total_dups}")

# If duplicates exist, inspect them before dropping
if total_dups > 0:
    print("Sample of duplicate rows:")
    print(df[df.duplicated(keep=False)])

Total fully duplicate rows: 0

# Check Missing Values

In [11]:
missing = df.isna().sum()
missing_pct = (df.isna().sum() / len(df) * 100).round(2)

missing_report = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_pct
}).sort_values('Missing %', ascending=False)


print("Missing Value Report:")
print(missing_report[missing_report['Missing Count'] > 0].to_string())

Missing Value Report:
                                   Missing Count  Missing %
incomplete_rides_reason                   141000       94.0
incomplete_rides                          141000       94.0
reason_for_cancelling_by_customer         139500       93.0
cancelled_rides_by_customer               139500       93.0
cancelled_rides_by_driver                 123000       82.0
driver_cancellation_reason                123000       82.0
customer_rating                            57000       38.0
driver_ratings                             57000       38.0
ride_distance                              48000       32.0
booking_value                              48000       32.0
payment_method                             48000       32.0

In [12]:
for col in ['reason_for_cancelling_by_customer', 'driver_cancellation_reason', 'incomplete_rides_reason']:
    df[col] = df[col].fillna('Not Applicable')
    print(f"✅ '{col}' filled with 'Not Applicable'")

✅ 'reason_for_cancelling_by_customer' filled with 'Not Applicable'
✅ 'driver_cancellation_reason' filled with 'Not Applicable'
✅ 'incomplete_rides_reason' filled with 'Not Applicable'

In [13]:
for col in ['cancelled_rides_by_customer', 'cancelled_rides_by_driver', 'incomplete_rides', 'booking_value', 'ride_distance']:
    df[col] = df[col].fillna('0')
    print(f"✅ '{col}' filled with '0'")

✅ 'cancelled_rides_by_customer' filled with '0'
✅ 'cancelled_rides_by_driver' filled with '0'
✅ 'incomplete_rides' filled with '0'
✅ 'booking_value' filled with '0'
✅ 'ride_distance' filled with '0'

In [14]:
for col in ['payment_method']:
    df[col] = df[col].fillna('No Payment')
    print(f"✅ '{col}' filled with 'No Payment'")

✅ 'payment_method' filled with 'No Payment'

In [15]:
df

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,cancelled_rides_by_customer,reason_for_cancelling_by_customer,cancelled_rides_by_driver,driver_cancellation_reason,incomplete_rides,incomplete_rides_reason,booking_value,ride_distance,driver_ratings,customer_rating,payment_method
0,2025-09-22,06:39:39,T1984811,Cancelled by Customer,C6701334,Auto,Dilshad Garden,Qutub Minar,1.0,Change of plans,0,Not Applicable,0,Not Applicable,0,0,NaN,NaN,No Payment
1,2025-06-14,11:41:45,T2969701,Cancelled by Customer,C1401223,Auto,Delhi Gate,Chandni Chowk,1.0,Change of plans,0,Not Applicable,0,Not Applicable,0,0,NaN,NaN,No Payment
2,2025-10-10,12:56:23,T6336375,Cancelled by Customer,C7874381,Auto,Laxmi Nagar,IGNOU Road,1.0,Change of plans,0,Not Applicable,0,Not Applicable,0,0,NaN,NaN,No Payment
3,2025-07-30,10:39:07,T1997739,Cancelled by Customer,C3565599,Auto,Seelampur,Kalkaji,1.0,Change of plans,0,Not Applicable,0,Not Applicable,0,0,NaN,NaN,No Payment
4,2025-06-15,08:37:03,T9352835,Cancelled by Customer,C4457487,Auto,Manesar,Old Gurgaon,1.0,Change of plans,0,Not Applicable,0,Not Applicable,0,0,NaN,NaN,No Payment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2025-06-29,22:53:26,T3441703,Completed,C3345887,Auto,Udyog Vihar,Kaushambi,0,Not Applicable,0,Not Applicable,0,Not Applicable,300.0,44.72,4.2,4.9,UPI
149996,2025-05-08,16:36:23,T5412815,Completed,C7457601,Auto,Shastri Nagar,Gurgaon Railway Station,0,Not Applicable,0,Not Applicable,0,Not Applicable,328.0,34.35,4.2,4.9,UPI
149997,2025-07-15,17:16:41,T4359237,Completed,C9229149,Auto,Karol Bagh,Udyog Vihar,0,Not Applicable,0,Not Applicable,0,Not Applicable,141.0,25.4,4.2,4.9,UPI
149998,2025-12-08,09:18:33,T5006207,Completed,C8892560,Auto,Karol Bagh,Vaishali,0,Not Applicable,0,Not Applicable,0,Not Applicable,2045.0,37.85,4.2,4.9,UPI
149999,2025-12-24,19:29:32,T2260698,Completed,C6573059,Auto,Khandsa,Botanical Garden,0,Not Applicable,0,Not Applicable,0,Not Applicable,654.0,5.06,4.2,4.9,UPI